### ISSUE TITLE
Rails 7 page transitions

### ISSUE THREAD

**Issue by ryw** [railsjazz/peity_vanilla_rails#3] opened 2022-05-23 16:40 UTC
I just added charts to https://www.ossrank.com today, and the charts load on first page, but then when clicking into a project, the chart doesn't load. Refresh loads it on that page, but going back to index, those charts don't load.

Something with Rails 7 I don't understand for sure -- any ideas? 

I added  via:

1. Adding `gem "peity_vanilla_rails"` to `Gemfile`
2. Added `import "peity-vanilla-rails"` to `app/javascript/application.js`

**Comment by ryw** [comment] 2022-05-23 19:36
Happy to create an example repo to reproduce the problem, if you'd like me to...

**Comment by manastyretskyi** [comment] 2022-05-24 06:58
Hi, while navigating your website I was able to reproduce the problem, but it looks like it is not the problem with the library itself, if you open browser console, you will see errors like this.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/43040379/169967772-28f50ce4-5cc8-4364-8718-74a87b0bc9a1.png">
So it appears that there is the problem with you JavaScript, I would suggest you to try to fix it, and if the problem still remains, please create the sample repo where it reproduces.

**Comment by igorkasyanchuk** [comment] 2022-05-24 07:02
Also, I suggest adding pagination or lazy loading on the home page, because the page is just too big and have negative impact on it

**Comment by manastyretskyi** [comment] 2022-05-24 18:37
I believe I found out what the problem is after looking a little more closely at what happens on your website.
It appears that JavaScript was executed before DOM was ready, because of it mutation observer was not working.
I released version [0.2.1](https://github.com/railsjazz/peity_vanilla_rails/releases/tag/v0.2.1), now charts should work properly.
I would still suggest to fix your JavaScript through ;-)

**Comment by ryw** [comment] 2022-05-24 20:17
Thanks - will look at my JS, and pagination is near the top of the todo list :)

**Comment by ryw** [comment] 2022-05-24 21:05
Fixed JS error on my site, didn't resolve this issue.
I reproduced issue within a minimal Rails 7.0.3 app here:
https://github.com/ryw/peity_rails_7_test

Tested w/ latest Chrome + Safari to ensure it wasn't a browser issue too.

**Comment by manastyretskyi** [comment] 2022-05-25 07:40
Thank you for this example,
I've released new version [0.2.2](https://github.com/railsjazz/peity_vanilla_rails/releases/tag/v0.2.2), not this issue should be fixed for good.

**Closed** 2022-05-25 13:59 UTC
